version: "3.8"

services:
  ms_sql:
    container_name: "ms_sql"
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - "sqldata1:/var/opt/mssql"
      - "./backup:/backup"
    env_file:
      - .env
    network_mode: "bridge"

volumes:
  sqldata1:
